{
 "title": "etcd-cluster-info",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": "label_values({job=\"etcd\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Resource Usage",
   "type": "row",
   "gridPos": { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"openshift-etcd\", container=\"etcd\"}[2m])) by (pod) * 100",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(container_memory_working_set_bytes{container=\"\",pod!=\"\", namespace=~\"openshift-etcd.*\"}[2m])) BY (pod, namespace)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Disk WAL Sync Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_wal_fsync_duration_seconds_bucket[2m])) by (pod, le))",
       "legendFormat": "{{pod}} WAL fsync"
      }
     ]
    },
    {
     "title": "Disk Backend Sync Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_backend_commit_duration_seconds_bucket[2m])) by (pod, le))",
       "legendFormat": "{{pod}} DB fsync"
      }
     ]
    },
    {
     "title": "Etcd container disk writes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_writes_bytes_total{container=\"etcd\",device!~\".+dm.+\"}[2m])",
       "legendFormat": "{{ pod }}: {{ device }}"
      }
     ]
    },
    {
     "title": "DB Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "etcd_mvcc_db_total_size_in_bytes",
       "legendFormat": "{{pod}} DB physical size"
      },
      {
       "expr": "etcd_mvcc_db_total_size_in_use_in_bytes",
       "legendFormat": "{{pod}} DB logical size"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "row",
   "gridPos": { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
   "collapsed": true,
   "panels": [
    {
     "title": "Container network traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{ container=\"etcd\", namespace=~\"openshift-etcd.*\"}[2m])) BY (namespace, pod)",
       "legendFormat": "rx {{ pod }}"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{ container=\"etcd\", namespace=~\"openshift-etcd.*\"}[2m])) BY (namespace, pod)",
       "legendFormat": "tx {{ pod }}"
      }
     ]
    },
    {
     "title": "p99 peer to peer latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[2m]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Peer network traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(etcd_network_peer_received_bytes_total[2m])",
       "legendFormat": "rx {{pod}} Peer Traffic"
      },
      {
       "expr": "rate(etcd_network_peer_sent_bytes_total[2m])",
       "legendFormat": "tx {{pod}} Peer Traffic"
      }
     ]
    },
    {
     "title": "gRPC network traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(etcd_network_client_grpc_received_bytes_total[2m])",
       "legendFormat": "rx {{pod}}"
      },
      {
       "expr": "rate(etcd_network_client_grpc_sent_bytes_total[2m])",
       "legendFormat": "tx {{pod}}"
      }
     ]
    },
    {
     "title": "Active Streams",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
       "legendFormat": "Watch Streams"
      },
      {
       "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
       "legendFormat": "Lease Streams"
      }
     ]
    },
    {
     "title": "Snapshot duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum[2m]))",
       "legendFormat": "the total latency distributions of save called by snapshot"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Info per Member",
   "type": "row",
   "gridPos": { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
   "collapsed": true,
   "panels": [
    {
     "title": "% DB Space Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(etcd_mvcc_db_total_size_in_bytes{} / etcd_server_quota_backend_bytes{})*100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "DB Left capacity (with fragmented space)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "etcd_server_quota_backend_bytes{} - etcd_mvcc_db_total_size_in_bytes{}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "DB Size Limit (Backend-bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "etcd_server_quota_backend_bytes{}",
       "legendFormat": "{{ pod }} Quota Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "General Info",
   "type": "row",
   "gridPos": { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft Proposals",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_server_proposals_failed_total[2m]))",
       "legendFormat": "Proposal Failure Rate"
      },
      {
       "expr": "sum(etcd_server_proposals_pending)",
       "legendFormat": "Proposal Pending Total"
      },
      {
       "expr": "sum(rate(etcd_server_proposals_committed_total[2m]))",
       "legendFormat": "Proposal Commit Rate"
      },
      {
       "expr": "sum(rate(etcd_server_proposals_applied_total[2m]))",
       "legendFormat": "Proposal Apply Rate"
      }
     ]
    },
    {
     "title": "Number of leader changes seen",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(etcd_server_leader_changes_seen_total[2m]))"
      }
     ]
    },
    {
     "title": "Etcd has a leader?",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "max(etcd_server_has_leader)" }
     ]
    },
    {
     "title": "Total number of failed proposals seen",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(etcd_server_proposals_committed_total)"
      }
     ]
    },
    {
     "title": "Leader Elections Per Day",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(etcd_server_leader_changes_seen_total[1d])",
       "legendFormat": "{{instance}} Total Leader Elections Per Day"
      }
     ]
    },
    {
     "title": "Keys",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "etcd_debugging_mvcc_keys_total{pod=~\"$pod\"}",
       "legendFormat": "{{ pod }} Num keys"
      }
     ]
    },
    {
     "title": "Slow Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "delta(etcd_server_slow_apply_total{pod=~\"$pod\"}[2m])",
       "legendFormat": "{{ pod }} slow applies"
      },
      {
       "expr": "delta(etcd_server_slow_read_indexes_total{pod=~\"$pod\"}[2m])",
       "legendFormat": "{{ pod }} slow read indexes"
      }
     ]
    },
    {
     "title": "Key Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(etcd_debugging_mvcc_put_total{pod=~\"$pod\"}[2m])",
       "legendFormat": "{{ pod }} puts/s"
      },
      {
       "expr": "rate(etcd_debugging_mvcc_delete_total{pod=~\"$pod\"}[2m])",
       "legendFormat": "{{ pod }} deletes/s"
      }
     ]
    },
    {
     "title": "Heartbeat Failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "etcd_server_heartbeat_send_failures_total{pod=~\"$pod\"}",
       "legendFormat": "{{ pod }} heartbeat  failures"
      },
      {
       "expr": "etcd_server_health_failures{pod=~\"$pod\"}",
       "legendFormat": "{{ pod }} health failures"
      }
     ]
    },
    {
     "title": "Compacted Keys",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "etcd_debugging_mvcc_db_compaction_keys_total{pod=~\"$pod\"}",
       "legendFormat": "{{ pod  }} keys compacted"
      }
     ]
    }
   ]
  }
 ]
}