{
 "title": "OpenShift Performance",
 "description": "Performance dashboard for Red Hat OpenShift",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "_master_node",
    "label": "Master",
    "query": "label_values(kube_node_role{role=\"master\"}, node)"
   },
   {
    "name": "_worker_node",
    "label": "Worker",
    "query": "label_values(kube_node_role{role=~\"work.*\"}, node)"
   },
   {
    "name": "_infra_node",
    "label": "Infra",
    "query": "label_values(kube_node_role{role=\"infra\"}, node)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "block_device",
    "label": "Block device",
    "query": "label_values(node_disk_written_bytes_total,device)"
   },
   {
    "name": "net_device",
    "label": "Network device",
    "query": "label_values(node_network_receive_bytes_total,device)"
   },
   { "name": "interval", "label": "interval", "query": "2m,3m,4m,5m" }
  ]
 },
 "panels": [
  {
   "title": "OVN",
   "type": "row",
   "gridPos": { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Annotation Latency",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(ovnkube_master_pod_creation_latency_seconds_sum[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CNI Request ADD Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(ovnkube_node_cni_request_duration_seconds_sum{command=\"ADD\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CNI Request DEL Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(ovnkube_node_cni_request_duration_seconds_sum{command=\"DEL\"}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "br-int Flow Count",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "ovnkube_node_integration_bridge_openflow_total",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring stack",
   "type": "row",
   "gridPos": { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Replica Memory usage",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{pod=\"prometheus-k8s-1\",namespace!=\"\",name!=\"\",container=\"prometheus\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(container_memory_rss{pod=\"prometheus-k8s-0\",namespace!=\"\",name!=\"\",container=\"prometheus\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Kubelet",
   "type": "row",
   "gridPos": { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Kubelet CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(10,rate(process_cpu_seconds_total{service=\"kubelet\",job=\"kubelet\"}[$interval])*100)",
       "legendFormat": "kubelet - {{node}}"
      }
     ]
    },
    {
     "title": "Top 10 crio CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(10,rate(process_cpu_seconds_total{service=\"kubelet\",job=\"crio\"}[$interval])*100)",
       "legendFormat": "crio - {{node}}"
      }
     ]
    },
    {
     "title": "Top 10 Kubelet memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10,process_resident_memory_bytes{service=\"kubelet\",job=\"kubelet\"})",
       "legendFormat": "kubelet - {{node}}"
      }
     ]
    },
    {
     "title": "Top 10 crio memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10,process_resident_memory_bytes{service=\"kubelet\",job=\"crio\"})",
       "legendFormat": "crio - {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Details",
   "type": "row",
   "gridPos": { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Node Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_node_info{})", "legendFormat": "Number of nodes" },
      {
       "expr": "sum(kube_node_status_condition{status=\"true\"}) by (condition) > 0",
       "legendFormat": "Node: {{ condition }}"
      }
     ]
    },
    {
     "title": "Current Namespace Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kube_namespace_created{})",
       "legendFormat": "Namespace Count"
      }
     ]
    },
    {
     "title": "Current Pod Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{}) by (phase) > 0",
       "legendFormat": "{{ phase}} Pods"
      }
     ]
    },
    {
     "title": "Number of nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "sum(kube_node_info{})", "legendFormat": "Number of nodes" },
      {
       "expr": "sum(kube_node_status_condition{status=\"true\"}) by (condition) > 0",
       "legendFormat": "Node: {{ condition }}"
      }
     ]
    },
    {
     "title": "Namespace count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "count(kube_namespace_created{})",
       "legendFormat": "Namespace count"
      }
     ]
    },
    {
     "title": "Pod count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{}) by (phase)",
       "legendFormat": "{{phase}} pods"
      }
     ]
    },
    {
     "title": "Secret & configmap count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "count(kube_secret_info{})", "legendFormat": "secrets" },
      { "expr": "count(kube_configmap_info{})", "legendFormat": "Configmaps" }
     ]
    },
    {
     "title": "Deployment count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "count(kube_deployment_labels{})",
       "legendFormat": "Deployments"
      }
     ]
    },
    {
     "title": "Services count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "count(kube_service_info{})", "legendFormat": "Services" }
     ]
    },
    {
     "title": "Routes count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "count(openshift_route_info{})", "legendFormat": "Routes" }
     ]
    },
    {
     "title": "Alerts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum(ALERTS{severity!=\"none\"}) by (alertname, severity))",
       "legendFormat": "{{severity}}: {{alertname}}"
      }
     ]
    },
    {
     "title": "Top 10 container RSS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, container_memory_rss{namespace!=\"\",container!=\"POD\",name!=\"\"})",
       "legendFormat": "{{ namespace }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Top 10 container CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(10,irate(container_cpu_usage_seconds_total{namespace!=\"\",container!=\"POD\",name!=\"\"}[$interval])*100)",
       "legendFormat": "{{ namespace }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Goroutines count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(go_goroutines{}) by (job,instance))",
       "legendFormat": "{{ job }} - {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Operators Details",
   "type": "row",
   "gridPos": { "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster operators overview",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by (condition)(cluster_operator_conditions{condition!=\"\"})",
       "legendFormat": "{{ condition }}"
      }
     ]
    },
    {
     "title": "Cluster operators information",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "cluster_operator_conditions{name!=\"\",reason!=\"\"}",
       "legendFormat": "{{name}} - {{reason}}"
      }
     ]
    },
    {
     "title": "Cluster operators degraded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "cluster_operator_conditions{condition=\"Degraded\",name!=\"\",reason!=\"\"}",
       "legendFormat": "{{name}} - {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Master: $_master_node",
   "type": "row",
   "gridPos": { "gridPos": { "h": 8, "w": 0, "x": 0, "y": 1 } },
   "repeat": "_master_node",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (instance, mode)(rate(node_cpu_seconds_total{instance=~\"$_master_node\",job=~\".*\"}[$interval])) * 100",
       "legendFormat": "Busy {{mode}}"
      }
     ]
    },
    {
     "title": "System Memory: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Active_bytes{instance=~\"$_master_node\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$_master_node\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$_master_node\"} + node_memory_Buffers_bytes{instance=~\"$_master_node\"}",
       "legendFormat": "Cached + Buffers"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$_master_node\"} - (node_memory_Cached_bytes{instance=~\"$_master_node\"} + node_memory_Buffers_bytes{instance=~\"$_master_node\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Disk throughput: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{device=~\"$block_device\",instance=~\"$_master_node\"}[$interval])",
       "legendFormat": "{{ device }} - read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{device=~\"$block_device\",instance=~\"$_master_node\"}[$interval])",
       "legendFormat": "{{ device }} - write"
      }
     ]
    },
    {
     "title": "Disk IOPS: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{device=~\"$block_device\",instance=~\"$_master_node\"}[$interval])",
       "legendFormat": "{{ device }} - read"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{device=~\"$block_device\",instance=~\"$_master_node\"}[$interval])",
       "legendFormat": "{{ device }} - write"
      }
     ]
    },
    {
     "title": "Network Utilization: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$_master_node\",device=~\"$net_device\"}[$interval]) * 8",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$_master_node\",device=~\"$net_device\"}[$interval]) * 8",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network Packets: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{instance=~\"$_master_node\",device=~\"$net_device\"}[$interval])",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{instance=~\"$_master_node\",device=~\"$net_device\"}[$interval])",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network packets drop: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(node_network_receive_drop_total{instance=~\"$_master_node\"}[$interval]))",
       "legendFormat": "rx-drop-{{ device }}"
      },
      {
       "expr": "topk(10,rate(node_network_transmit_drop_total{instance=~\"$_master_node\"}[$interval]))",
       "legendFormat": "tx-drop-{{ device }}"
      }
     ]
    },
    {
     "title": "Conntrack stats: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=~\"$_master_node\"}",
       "legendFormat": "conntrack_entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=~\"$_master_node\"}",
       "legendFormat": "conntrack_limit"
      }
     ]
    },
    {
     "title": "Top 10 container CPU: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container!=\"POD\",name!=\"\",node=~\"$_master_node\",namespace!=\"\",namespace=~\"$namespace\"}[$interval])) by (pod,container,namespace,name,service) * 100)",
       "legendFormat": "{{ pod }}: {{ container }}"
      }
     ]
    },
    {
     "title": "Top 10 container RSS: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, container_memory_rss{container!=\"POD\",name!=\"\",node=~\"$_master_node\",namespace!=\"\",namespace=~\"$namespace\"})",
       "legendFormat": "{{ pod }}: {{ container }}"
      }
     ]
    },
    {
     "title": "Container fs write rate: $_master_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{device!~\".+dm.+\", node=~\"$_master_node\", container!=\"\"}[$interval])) by (device, container)",
       "legendFormat": "{{ container }}: {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker: $_worker_node",
   "type": "row",
   "gridPos": { "gridPos": { "h": 8, "w": 0, "x": 0, "y": 1 } },
   "repeat": "_worker_node",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic: $_worker_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (instance, mode)(rate(node_cpu_seconds_total{instance=~\"$_worker_node\",job=~\".*\"}[$interval])) * 100",
       "legendFormat": "Busy {{mode}}"
      }
     ]
    },
    {
     "title": "System Memory: $_worker_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Active_bytes{instance=~\"$_worker_node\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$_worker_node\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$_worker_node\"} + node_memory_Buffers_bytes{instance=~\"$_worker_node\"}",
       "legendFormat": "Cached + Buffers"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$_worker_node\"} - (node_memory_Cached_bytes{instance=~\"$_worker_node\"} + node_memory_Buffers_bytes{instance=~\"$_worker_node\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Disk throughput: $_worker_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{device=~\"$block_device\",instance=~\"$_worker_node\"}[$interval])",
       "legendFormat": "{{ device }} - read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{device=~\"$block_device\",instance=~\"$_worker_node\"}[$interval])",
       "legendFormat": "{{ device }} - write"
      }
     ]
    },
    {
     "title": "Disk IOPS: $_worker_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{device=~\"$block_device\",instance=~\"$_worker_node\"}[$interval])",
       "legendFormat": "{{ device }} - read"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{device=~\"$block_device\",instance=~\"$_worker_node\"}[$interval])",
       "legendFormat": "{{ device }} - write"
      }
     ]
    },
    {
     "title": "Network Utilization: $_worker_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$_worker_node\",device=~\"$net_device\"}[$interval]) * 8",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$_worker_node\",device=~\"$net_device\"}[$interval]) * 8",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network Packets: $_worker_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{instance=~\"$_worker_node\",device=~\"$net_device\"}[$interval])",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{instance=~\"$_worker_node\",device=~\"$net_device\"}[$interval])",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network packets drop: $_worker_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(node_network_receive_drop_total{instance=~\"$_worker_node\"}[$interval]))",
       "legendFormat": "rx-drop-{{ device }}"
      },
      {
       "expr": "topk(10,rate(node_network_transmit_drop_total{instance=~\"$_worker_node\"}[$interval]))",
       "legendFormat": "tx-drop-{{ device }}"
      }
     ]
    },
    {
     "title": "Conntrack stats: $_worker_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=~\"$_worker_node\"}",
       "legendFormat": "conntrack_entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=~\"$_worker_node\"}",
       "legendFormat": "conntrack_limit"
      }
     ]
    },
    {
     "title": "Top 10 container CPU: $_worker_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container!=\"POD\",name!=\"\",node=~\"$_worker_node\",namespace!=\"\",namespace=~\"$namespace\"}[$interval])) by (pod,container,namespace,name,service) * 100)",
       "legendFormat": "{{ pod }}: {{ container }}"
      }
     ]
    },
    {
     "title": "Top 10 container RSS: $_worker_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, container_memory_rss{container!=\"POD\",name!=\"\",node=~\"$_worker_node\",namespace!=\"\",namespace=~\"$namespace\"})",
       "legendFormat": "{{ pod }}: {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infra: $_infra_node",
   "type": "row",
   "gridPos": { "gridPos": { "h": 8, "w": 0, "x": 0, "y": 1 } },
   "repeat": "_infra_node",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic: $_infra_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (instance, mode)(rate(node_cpu_seconds_total{instance=~\"$_infra_node\",job=~\".*\"}[$interval])) * 100",
       "legendFormat": "Busy {{mode}}"
      }
     ]
    },
    {
     "title": "System Memory: $_infra_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Active_bytes{instance=~\"$_infra_node\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$_infra_node\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$_infra_node\"} + node_memory_Buffers_bytes{instance=~\"$_infra_node\"}",
       "legendFormat": "Cached + Buffers"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$_infra_node\"} - (node_memory_Cached_bytes{instance=~\"$_infra_node\"} + node_memory_Buffers_bytes{instance=~\"$_infra_node\"})",
       "legendFormat": "Available"
      }
     ]
    },
    {
     "title": "Disk throughput: $_infra_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{device=~\"$block_device\",instance=~\"$_infra_node\"}[$interval])",
       "legendFormat": "{{ device }} - read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{device=~\"$block_device\",instance=~\"$_infra_node\"}[$interval])",
       "legendFormat": "{{ device }} - write"
      }
     ]
    },
    {
     "title": "Disk IOPS: $_infra_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{device=~\"$block_device\",instance=~\"$_infra_node\"}[$interval])",
       "legendFormat": "{{ device }} - read"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{device=~\"$block_device\",instance=~\"$_infra_node\"}[$interval])",
       "legendFormat": "{{ device }} - write"
      }
     ]
    },
    {
     "title": "Network Utilization: $_infra_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$_infra_node\",device=~\"$net_device\"}[$interval]) * 8",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$_infra_node\",device=~\"$net_device\"}[$interval]) * 8",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network Packets: $_infra_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{instance=~\"$_infra_node\",device=~\"$net_device\"}[$interval])",
       "legendFormat": "{{instance}} - {{device}} - RX"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{instance=~\"$_infra_node\",device=~\"$net_device\"}[$interval])",
       "legendFormat": "{{instance}} - {{device}} - TX"
      }
     ]
    },
    {
     "title": "Network packets drop: $_infra_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "topk(10, rate(node_network_receive_drop_total{instance=~\"$_infra_node\"}[$interval]))",
       "legendFormat": "rx-drop-{{ device }}"
      },
      {
       "expr": "topk(10,rate(node_network_transmit_drop_total{instance=~\"$_infra_node\"}[$interval]))",
       "legendFormat": "tx-drop-{{ device }}"
      }
     ]
    },
    {
     "title": "Conntrack stats: $_infra_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=~\"$_infra_node\"}",
       "legendFormat": "conntrack_entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=~\"$_infra_node\"}",
       "legendFormat": "conntrack_limit"
      }
     ]
    },
    {
     "title": "Top 10 container CPU: $_infra_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container!=\"POD\",name!=\"\",node=~\"$_infra_node\",namespace!=\"\",namespace=~\"$namespace\"}[$interval])) by (pod,container,namespace,name,service) * 100)",
       "legendFormat": "{{ pod }}: {{ container }}"
      }
     ]
    },
    {
     "title": "Top 10 container RSS: $_infra_node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, container_memory_rss{container!=\"POD\",name!=\"\",node=~\"$_infra_node\",namespace!=\"\",namespace=~\"$namespace\"})",
       "legendFormat": "{{ pod }}: {{ container }}"
      }
     ]
    }
   ]
  }
 ]
}