apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: flowcollector-template
objects:
  - apiVersion: flows.netobserv.io/v1beta2
    kind: FlowCollector
    metadata:
      name: cluster
    spec:
      namespace: netobserv
      deploymentModel: "${DeploymentModel}"
      agent:
        type: eBPF
        ebpf:
          sampling: ${{EBPFSamplingRate}}
          cacheMaxFlows: ${{EBPFCacheMaxFlows}}
          privileged: "${{EBPFPrivileged}}"
          resources:
            limits:
              memory: ${EBPFMemoryLimit}
      processor:
        resources:
          limits:
            memory: ${FLPMemoryLimit}
        kafkaConsumerReplicas: ${{KafkaConsumerReplicas}}
      kafka:
        address: kafka-cluster-kafka-bootstrap.netobserv
        topic: network-flows
        tls:
          enable: false
      loki:
        mode: LokiStack
        enable: "${{LokiEnable}}"
parameters:
  - name: DeploymentModel
    value: "Kafka"
  - name: EBPFSamplingRate
    value: "1"
  - name: EBPFMemoryLimit
    value: "800Mi"
  - name: FLPMemoryLimit
    value: "800Mi"
  - name: EBPFPrivileged
    value: "false"
  - name: EBPFCacheMaxFlows
    value: "100000"
  - name: LokiEnable
    value: "true"
  - name: KafkaConsumerReplicas
    value: "3"
